name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - numpy==1.26.2
  - matplotlib==3.8.2
  - scikit-learn==1.3.2
  - ipywidgets==8.1.5
  - voila==0.5.4
