name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - numpy==1.26.2
  - matplotlib==3.8.2
  - scipy
  - ipywidgets==8.1.5
  - ipecharts
  - pandas
  - bqplot
