name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - numpy==1.26.4
  - matplotlib
  - scipy
  - ipywidgets==8.1.7
  - ipecharts
  - pandas
  - bqplot
  - pybind11>=2.12
  - python<=3.11
