name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - scipy
  - ipywidgets
  - ipecharts
  - pandas
  - bqplot
